[workspace]
members = [
	"node",
	"protocol",
	"start-jeager",
	"client",
	"testing",
	"benchmark",
]

[patch.crates-io]
instance-chart = { git = "https://github.com/dvdsk/instance-chart" }

[profile.release]
debug = true
