[workspace]
members = [
	"node",
	"protocol",
	"start-jeager",
]

[patch.crates-io]
tokio = { git = "https://github.com/tokio-rs/tokio", rev="0d4d3c3" }
tokio-util = { git = "https://github.com/tokio-rs/tokio", rev = "0d4d3c3" }
