[package]
name = "node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multicast-discovery = { git = "https://github.com/dvdsk/multicast-discovery.git" }
tokio = { version = "1.0", features = ["macros", "net", "time", "rt-multi-thread"] }

clap = { version = "3.1", features = ["derive"] }

tracing = "0.1.33"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
tracing-opentelemetry = { version = "0.17.2" }
opentelemetry-jaeger = { version = "0.16.0", features = ["rt-tokio"] }
opentelemetry = { version = "0.17", features = ["rt-tokio"] }

color-eyre = "0.6"

sled = "0.34"

[dev-dependencies]
start-jeager = { path = "../start-jeager" }
